exclude: |
  (?x)^(
      (?:.*/)?(
          logs/|
          reports/|
          allure-results/|
          screenshots/|
          node_modules/|
          venv/|
          \.venv/|
          backup/
      )
  )


repos:
  - repo: local
    hooks:
      - id: block-ssh-git-dependencies
        name: Block Git SSH Dependencies in requirements.txt
        entry: .git/hooks/block_ssh_git.sh
        language: script
        types: [text]
        files: ^requirements\.txt$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        args: ["--line-length=100"]

  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile=black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8 (nrobo lint)
        args: ["--config=.flake8", "src"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "nrobo/"]
