[build-system]
requires = ["setuptools>=68.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "nrobo"
version = "2025.1.0"
description = "A Pytest-powered Smart Test Runner CLI tool."
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "Panchdev Singh Chauhan", email = "erpanchdev@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
  "pytest>=7.0",
  "pyyaml",
  "typer>=0.9",
  "rich",
  "pytest-html>=4.0.0",
  "allure-pytest>=2.13.5",
  "colorlog>=6.8.2",
  "selenium>=4.12.0",
  "Appium-Python-Client>=2.11.1",
  "webdriver-manager>=4.0.1",
]

[project.scripts]
nrobo = "nrobo.cli:main"

[tool.setuptools.package-data]
"nrobo" = ["templates/*"]

[project.entry-points.pytest11]
nrobo = "nrobo.plugins.nrobo_plugin"

[tool.bandit]
skips = ["B607", "B101", "B603", "B404"]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "pre-commit",
  "flake8",
  "codecov",
  "allure-pytest",
  "colorlog>=6.8.2",
  "selenium>=4.12.0",
  "Appium-Python-Client>=2.11.1",
  "webdriver-manager>=4.0.1",
]

# pyproject.toml

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

[flake8]
ignore = ["E501"]
max-line-length = 120   # optional: bump limit instead of ignoring

[tool.coverage.run]
patch = ["subprocess"]
branch = true
source = ["."] # ["src/nrobo"]
omit = [
    "*/tests/*",
    "*/migrations/*",
    "*/__init__.py",
    "*/settings/*",
    "*/venv/*",
    "manage.py",
    "*/config/*",
    "*/apps.py",
    "*/__init__.py",
    "*/venv/*",
    "*/.venv/*",
    "*/node_modules/*",
    "*/backup/*",
    "*/selenium_wrappers/*",
    "build_and_publish.py",
]

[tool.coverage.report]
show_missing = true
skip_covered = true
precision = 2
exclude_lines = [
    "pragma: no cover",
    "def __str__",
    "if __name__ == '__main__':",
    "raise NotImplementedError",
    "except ImportError",
    "@abstractmethod"
]

[tool.coverage.html]
directory = "test_artifacts/coverage_reports/html"

[tool.coverage.xml]
output = "test_artifacts/coverage_reports/xml/coverage.xml"
