[build-system]
requires = ["setuptools>=68.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "nrobo"
version = "2025.0.0"
description = "A Pytest-powered Smart Test Runner CLI tool."
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "Panchdev Singh Chauhan", email = "erpanchdev@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
  "pytest>=7.0",
  "pyyaml",
  "typer>=0.9",
  "rich",
  "pytest-html>=4.0.0",
  "allure-pytest>=2.13.5",
]

[project.scripts]
nrobo = "nrobo.cli:main"

[tool.setuptools.package-data]
"nrobo" = ["templates/*"]
