name: CI

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jre
          sudo apt install -y gnupg2 wget
          java -version
          wget -qO - https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.25.0/allure-commandline-2.25.0.zip -O allure.zip
          sudo apt install unzip
          unzip allure.zip -d allure
          sudo mv allure/allure-* /opt/allure

          echo 'export PATH=$PATH:/opt/allure/bin' >> ~/.bashrc
          source ~/.bashrc
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
          allure --version
          pip install -r requirements.txt
          pip install -e .

      - name: Run lint
        run: python -m flake8 --config=configs/.flake8 src/nrobo

      - name: Run tests
        run: nrobo --coverage -n auto

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
